### ISSUE TITLE
panosc web site requirements

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#1]
This issue is for gathering the requirements for the PaNOSC project website.

Please add your needs, ideas and proposals for the PaNOSC website as comments to this issue.

**Comment by andygotz** [comment]
The main role of the PaNOSC official website will be to communicate the goals, progress and results to the partners, observers and scientific world. The website will contain largely static information. Internal communication will be done via other channels like slack, email and github. Some documents will be stored on the website but most of them will be on github or another document sharing platform. The goal is to keep the PaNOSC website simple but useful so that scientists can go there to find out how to adopt FAIR data management in their scientific workflow.

The following questions need discussion and answers:

* Do we need to change the logo?
* What should the structure of the website be?
* Should we move the pandata website contents to PaNOSC?
* How will we integrate the data services to the website?
* Who should be editors of the website?

One requirement is that the website is based on an open source solution and that the source code for the website is stored on github so that the cluster can continue to host the website after the project has ended.

Examples of other project websites which could serve as inspiration are:

* https://opendreamkit.org/
* https://phenomenal-h2020.eu
* http://www.opensesame-h2020.eu/en/
* https://www.ceric-eric.eu/

**Comment by zjttoefs** [comment]
Another example: https://brightness.esss.se/

**Comment by fangohr** [comment]
I am happy with the logo, although running this past professionals to polish is probably a good idea (create vector graphics/high res versions).

**Comment by fangohr** [comment]
For hosting of webpages: 

GitHub-pages offers to host webpages that are based on static html (https://pages.github.com).

Examples are: 
- http://opendreamkit.org
- https://fangohr.github.io

Github.io can also render source to html automatically when changes are pushed to that repository. It uses the Jekyll webpage generator (it uses a particular flavour known as github-pages):

Tutorial (there are probably better ones): 

- https://jekyllrb.com/docs/github-pages/
- https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/
- To use Jekyll for github pages locally: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

This is useful, as pages render automatically when changes are pushed, but it needs one or two people who know (or can learn) the Jekyll language (and can change structure of webpage etc when required). Updating text in existing pages, or adding a newpage that fits into an existing framework is relatively easy, and can be done by anybody who can edit a (mark-down) file.

**Comment by fangohr** [comment]
Web page requirements:

- persistent beyond project duration
- ability to change quickly, i.e. participants should be able to edit a file / edit a page through web interface to update news items, reports from events etc - without having to pass this via a single point of processing (and failure).
- from discussion this morning: mostly static html, with links to data services (which are hosted elsewhere).

**Comment by jamhall** [comment]
@fangohr  - For Jekyll, I've heard good things about https://forestry.io 
It's a nice web interface for managing Jekyll sites backed by GIT. Easier for editors to use than the standard Git/Jekyll workflow.

**Comment by NicolettaCarboni** [comment]
The one attached is a very first draft of the possible website's structure. I'd kindly ask the IT developers to think in particular about the content that shall be included in the "services" and "developments" (if the latter is needed) sections. Such pages would be meant to include a description of the service(s) developed and the links redirecting to data services hosted outside the PaNOSC website. 
Of course comments and suggestions are welcome on the overall structure and on the elements thought for each section.

Note: items in 1st level navigation menu would be clickable, therefore they'd redirect to pages with content, as well as of course all other items in 2nd level navigation menu.

![panoscweb_structurev1](https://user-images.githubusercontent.com/42873520/45291192-bf09ab00-b4f1-11e8-949c-f11be5650a85.png)

I personally have no experience with GitHub, but I'd rely on your advice if you consider it the best solution fulfilling our requirements. 
Wordpress would also be suitable to allow an easy update of the website by different users. The CMS is user friendly and probably most of us are already used to it. It seems it can also be linked to and synchronized with GitHub repository: https://it.wordpress.org/plugins/wp-github-sync/

**Comment by JBodera** [comment]
I propose to close down this issue for now.  
It could be reopened at any time (or a new issue created to further discuss this).

Please reply here by 22/11/2019 if you think this issue should remain open.
