### ISSUE TITLE
Data storage needs?

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#10]
STFC (3rd linked party to EGI.eu) asked about the data storage needs for PaNOSC during 2019.

JF Perrin suggested 1 PetaByte for 2019 during the conference call 12/11/2018. 

Please let us know if that sounds reasonable for you or not.

**Comment by RDimper** [comment]
Not sure what we will deposit on this storage space. In any case I think that 1PB is more than enough. We will not have enormous amounts of open data yet in 2019. Even for testing data analysis software the space is more than sufficient.
