### ISSUE TITLE
Work Package 5 Leader leaving

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#15]
Hi,

This issue is to highlight the fact that **@CFGrote is leaving**, therefore he won't be leading WP5 to its successful conclusion. While I wish the best of luck for Carsten in the future we need to be ready for this change in the project.

1. Will XFEL.eu appoint a person to replace Carsten who will be able to lead WP5?
2. If yes, can XFEL.eu appoint this person before the kick-off meeting?
2. If yes, we need to know who and invite this person to attend the kick-off meeting.
3. If not, will there be a handover within XFEL before Carsten leaves ? (end of February I think)
4. If that's the case that would be great, if not we need an interim WP5 lead
5. If XFEL.eu cannot appoint a replacement for any reason we will need to think about how to work this out.

**Comment by CFGrote** [comment]
Hi Jordi, thanks for bringing this up. As far as I know, XFEL is currently looking into various options and candidates to take over from me. It is assumed that this candidate will not show up before summer 2019. Therefore, we should nominate an interim WP leader. My understanding from conversation with @andygotz is that @srio (Manuel Sanchez-Rio) agreed to take this hat until he leaves into his sabbatical. With some luck, XFEL will have found someone until then. My apologies again for the bad timing.

**Comment by JBodera** [comment]
Closed as per PMC 19/12/2018. @srio will be interim wp leader until June. XFEL should have found someone by that point. If that looks unlikely we will reopen the issue
