### ISSUE TITLE
Draft Consortium Agreement

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#16]
A copy of the Draft Consortium agreement from our Legal officer has been shared with the WP leaders of PaNOSC.

We would like to obtain all feedback before 21st December 2018, so we can quickly proceed to integrate it, approve it and sign it.

**Comment by andygotz** [comment]
EGI, ELI-DC, and ESS agree with the draft.

EuXFEL want to reword the open source licence part to include close source.

**Comment by andygotz** [comment]
Final draft sent out on the 20/1/2019. SO far the following parties have provided feedback:

1. ESRF - OK
2. ILL - OK
3. ELI - OK
4. EuXFEL - OK
5. CERIC-ERIC - OK

We are missing feedback from ESS and EGI. We need to get their confirmation before we can send the document out for signing.

**Comment by JBodera** [comment]
ESRF's Legal Officer has shared the final version of the PaNOSC Consortium Agreement today.

**Comment by JBodera** [comment]
Quick update on the signature of the CA: 2 partners have yet to provide their signature pages: ILL and ELI.

**Comment by andygotz** [comment]
Only one now. ILL signature has been received. ELI has signed but we have not received it. 

We are almost there!

**Comment by JBodera** [comment]
With all signatures gathered this is now completed.
