### ISSUE TITLE
Press release about kickoff

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#17]
CERIC to prepare a press release for the starting of PaNOSC. The draft to be circulated to all partners for feedback. After that each partner to publish the press release via their communications channels. CERIC will handle the EC channels.

**Comment by NicolettaCarboni** [comment]
The first draft of the press release about PanOSC start is available at this link for your comments
https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP9%20Outreach%20and%20communication/PaNOSC_startDec2018_v1.docx

**Comment by JBodera** [comment]
Closed as per PMC 19/12/2018.
Press release went out.
