### ISSUE TITLE
Document storing in GitHub

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#19]
During the conference call 05/12/2018 https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP1%20Management/Meetings/Project%20Management%20Committee/2018-12-05%20Project%20Management%20Committee/2018-12-05%20PMC%20Summary.txt we discussed about how best to store documents.

The main points were:

1. GitHub is good for code, however binary documents don't diff well. **Do we want a different storage system for binary documents?**
2. GitHub is currently open for everyone. **Do we want a different storage for confidential documents?**
3. Not said during the conference call, but @fangohr pointed out that f**or videos a dedicated storage place could be useful**

**Jordi's view is:**

1. If several people need to work on the same document Google Docs proved very useful and I would like to continue using it. However once the document is completed a final version must always be stored in GitHub.
2. I agree a separate place for confidential documents is required
3. I have no opinion on this, if we could use the same place as for _2_ tailoring permissions in different folders then that would be great.

Please let us know your thoughts, or come up with a proposal

**Carsten's view is:**
2. we need a private repository. to this end, we'll have to apply to github as a scientific organization (which we are). this will allow us to create a limited number of private repositories under panosc-eu for
free. we could then store internal documents here. in the same way we can also create private code repos in case we're not happy with opensource from the start of development.

**Comment by fangohr** [comment]
Agree on all accounts:

- GitHub generally good
- no problem in my view to include small binary documents [all in one place is convenient]
- need a separate place for confidential documents; a repository would make sense to use the same technology and structure
- google docs is effective for multi-author work; moving a final version of the document into the github repository seems like a good practical way forward

**Comment by jamhall** [comment]
For Atlassian products ([Confluence](https://www.atlassian.com/software/confluence), [JIRA](https://www.atlassian.com/software/jira) etc.), we could apply for an Open Source License (self-hosted or cloud....ideally cloud): [https://www.atlassian.com/software/views/open-source-license-request](https://www.atlassian.com/software/views/open-source-license-request)

Confluence is excellent for writing technical documentation(diagrams, UML, revision history, class diagrams,  PDF export, search, live editing etc.), a great text editor, plugins, hierarchical document organisation, and team collaboration. We use it quite extensively at the ILL for our technical documentation and knowledge base. It also has an extensive permissions system where you can have confidential spaces and public spaces for your documents.

Whilst Github is excellent for code, personally, I don't think it has the same benefits that confluence brings us. Although markdown is great, it also has it's limitations.

Also, +1 for google docs. It was very useful during the proposal writing process.

**Comment by JBodera** [comment]
Closed as per PMC 19/12/2018
GitHub as main repository. If we need editing by multiple team members at the same time we will use Google Docs. If at some point this is not convenient we will open a new issue.
