### ISSUE TITLE
Write DMP for PaNOSC

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#20]
We need to write a Data Management Plan for PaNOSC. We can get help from 

1. DMPonline: https://dmponline.dcc.ac.uk/

2. other DMP plans on zenodo for example

**Comment by JBodera** [comment]
Should I use the https://dmponline.dcc.ac.uk/template_export/1612436782.pdf template (from the European Commission)?

It has the following points:
1. Data Summary
2. FAIR data
    2.1. Making data findable
    2.2. Making data openly accessible
    2.3. Making data interoperable
    2.4. Increase data reuse
3. Allocation of resources
4. Data security
5. Ethical aspects
6. Other

**Comment by andygotz** [comment]
DMPOnline is a tool for generating templates. The official guidelines for H2020 projects are described here:

http://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/open-access-data-management/data-management_en.htm

We need to first read the guidelines before filling in the template. The DMP is a living document i.e. we will update it at regular intervals throughout the project.

**Comment by JBodera** [comment]
Closed as per PMC 19/12/2018
This is for a deliverable due May 2019. ESRF started working on it.

**Comment by andygotz** [comment]
We need to follow this up. Can you put the draft on the google drive please so we can comment on it. Thanks!

**Comment by JBodera** [comment]
Submitted
