### ISSUE TITLE
Answer EOSC-Hub questions

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#21]
The following questions were posed by the EOSC-Hub to the EOSC-Hub Strategy Board:

QUESTIONS for the EOSC-hub Strategy Board

The EOSC-hub project is a seedbed for the EOSC Portal that is a gateway to EOSC services and resources (https://www.eosc-portal.eu/). Being a major instrument in developing the Portal, the EOSC-hub project should add value by diversifying its features and offering. Hence,

Q1. What should the Portal offer, beyond what exists now in the Portal and elsewhere, to attract various users?

Q2. Which directions or actions should EOSC-hub take and implement into the Portal to boost the interplay between disciplines, and thus, to accelerate novel science and innovations?

Q3. What kind of service delivery and brokering strategies should we exercise to attract committed FAIR compliant service providers?

Q4. What role can the portal play in facilitating the "B2B processes” between public entities, e.g computer centres to ERICs?

Q5. What are the (most important three) key success factors that the EOSC-hub need to meet from the point of view of user communities, service providers, funders?

We are asked to provide written feedback by 21/1/2019.  Your input is requested. Please add your answers and comments to this issue.

**Comment by andygotz** [comment]
Here is a first attempt at answering these questions. Comments and feedback welcome.

**Q1. What should the Portal offer, beyond what exists now in the Portal and elsewhere, to attract various users?**

The main purpose of the portal should be to promote Open Science and the services required to do this. Currently the portal is a collection of disparate services. It is not clear what is behind each category. Many services sound promising by name but when you click on them they are something else or only for a very specific community (e.g. Home>Data Management>Access to Open Data platforms leads to some obscure service which seems to be for fisheries). Some services are not services at all. When you try to use them they need special authorisation or simply do not work. It can take months to get access. This is not going to convince users to go there.

The goal of the portal needs to be more pragmatic and user oriented. Today it is like a library in which their are no or very few books the user is interested in. Most of the services are not interesting for most of the users. The 1st and 2nd level categories should address a wide range of users and be free and reliable. A 3rd or lower category could be for special communities.

**Q2. Which directions or actions should EOSC-hub take and implement into the Portal to boost the interplay between disciplines, and thus, to accelerate novel science and innovations?**

There should be a special section for encouraging cross disciplinary data searching with examples of how to combine data sets. This should be completed with tutorials, videos, how to documentation.

**Q3. What kind of service delivery and brokering strategies should we exercise to attract committed FAIR compliant service providers?**

The portal should offer free generic services for searching data, depositing data, transporting data, trying out compute resources without requiring more than registering for an account. The portal should also offer a platform for scientists to collaborate online.

**Q4. What role can the portal play in facilitating the "B2B processes” between public entities, e.g computer centres to ERICs?**

Most RIs have an office dedicated to Business Development. The EOSC portal developers should interact with the Business Development experts in the RIs e.g. RIs  (incl. computing centers or e-inrastructures) to speak to the  business developers at e.g. CSCS to find out how EOSC-hub can help them  provide their services to e.g. ESRF.

**Q5. What are the (most important three) key success factors that the EOSC-hub need to meet from the point of view of user communities, service providers, funders?**

Provide useful services for doing Open Science which do not exist already or are difficult or costly to access, be free / low cost and easy to use, be easy to find and reliable. Examples of successful platforms which work are the big ones like GitHub, GitLab, Facebook, AWS, Google Cloud, and from the educational / scientific community we have eduroam, zenodo, ResearchGate, arXiv. The portal should learn from successful open source projects on how to organise and run the EOSC portal and community. The current portal needs to change if it does not want to appear to users as not much more than a catalogue of disparate projects / services which are not well organised, difficult to search to find useful services.

**Comment by floriangliksohn** [comment]
Hi Andy,

I'm happy with the responses you're suggesting and don't have any immediate suggestions of corrections or additions.

I'm only wondering whether Q4 is referring to services to business users as your answer tends to suggest. The question is referring to "B2B processes” between public entities and my guess is that they are actually referring to the processes in the "value chain" between service providers such as e-infrastructures / HPCs, and research infrastructures.

If I'm correct, the question is then probably how far the portal should go into integrating data-related and computing services of service providers.

**Comment by thomasholmrod** [comment]
Hi Andy,

I have recently looked at the services provided by EOSC-hub and I fully agree with your answers. I am not exactly impressed. Some small comments:

Q1. It could be added that more information about who and how many use the services would be helpful (although I fear that it may discourage users rather than convincing them). Entry barrier should be reduced, testing out a service as a guest could be helpful. The registration process seems  antiquated. 

Q5. GitLab and ResearchGate immediately comes to my mind here.

**Comment by thomasholmrod** [comment]
Related to Q4 I had the same immediate reaction as @floriangliksohn. An easy fix would be to say RIs (incl. computing centers or e-inrastructures). E.g. speak to the business developers at e.g. CSCS to find out how EOSC-hub can help them provide their services to e.g. ESRF.

**Comment by andygotz** [comment]
OK thanks for the feedback concerning Q4. I have integrated your comments.

**Comment by JBodera** [comment]
As per PMC 23/01/2019 I close this issue
