### ISSUE TITLE
Financial Control for PaNOSC

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#23]
I think we need to start thinking how often and with how much detail we want to oversee our expenditures for PaNOSC.

My idea would be:
1. Each Work Package Leader is responsible for expenditure within their workpackage, while keeping informed the Project Management Committee
2. Each partner is at the same time responsible for their own expenses and linked 3rd parties
3. Of course this will require some communication, and that's one of the many reasons why we have the Project Management Committee meetings
4. At high level, we only need to follow how much we are spending, so we can take action in case of over or under spending.

**I've created a document for the point 4:** https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP1%20Management/KPIs/PaNOSC%20-%20FinancialControl_20181215.docx

**Comment by NicolettaCarboni** [comment]
I've forwarded the file to our Chief Administration Officer, who accepts the document as it is and has no further comments

**Comment by floriangliksohn** [comment]
I've also forwarded and checked the file with your Financial Officer. We're both happy with your suggestions and have no further comments.

**Comment by petraaulin** [comment]
our external relations office have had a look and say this financial report will be fine. No further comments

**Comment by JBodera** [comment]
Closed as per PMC 23/01/2019
