### ISSUE TITLE
1st Annual Meeting

### ISSUE THREAD

**Issue by darioceric** [panosc-eu/panosc#27]
CERIC-ERIC would be happy to host the 1st annual meeting in Trieste, if the rest of the partnership agrees.
We proposed the end of October or the beginning of November 2019.
I would like to ask you to add your comments, suggestions and availability to this issue.

**Comment by darioceric** [comment]
Jean-François (ILL), Andy and Rudolf (ESRF) agree with the CERIC-ERIC proposal: week 44 of 2019, from 28 October to 1 November

**Comment by JBodera** [comment]
The Chair of the Executive Board will share with the EB the proposed date and ask feedback ahead of the next PMC meeting (scheduled for 20/02/2019).

Ornela said that in week 44 Jana is not available. Rudolf cannot week 45, so we will try to book week 43.

**Comment by darioceric** [comment]
During the PMC meeting (27/02/2019) we proposed to have the meeting on Monday 21 and Tuesday 22 October 2019. Rudolf suggest to have the other two following days (23 and 24 October 2019) for the meetings related to individual WPs. 
CERIC-ERIC will try to confirm as soon as possible if the meetings will be in Elettra or in Trieste.

**Comment by darioceric** [comment]
Following the PMC meeting of Wednesday 10 April 2019, please find here the actual situation:
- the meeting will be hosted in Trieste, Savoia Excelsior Palace, from 14.00 to 18.00 of Monday 21 October and from 09.00 to 18.00 of Tuesday 22 October 2019.
- the two following days (23 and 24 October 2019) we will host the WPs meeting in Elettra.
- we forecast 100 people will attend the meetings
Questions:
- The EB meeting will be before, during or after the 1st annual meeting? 
Andy suggested not to overlap the EB meeting with neither the plenaries nor the WPs sessions. Rodolf suggested to do it after this two meetings (plenaries and WP sessions) because that would allow discussing issues arised from the workshop. What would you suggest? 
- The WPs meeting will be two full days? Probably one full day and half of the second? What do you think? 
As far as we will have an agenda, we will create a registration form. We will also put there some suggestions for the accommodation.

**Comment by JBodera** [comment]
Quick update: As per PMC meetings, the Annual Conference will be 4th and 5th November in Trieste.
The document -CONFIDENTIAL- should be used to fill in potential invitees.

**Comment by JBodera** [comment]
Annual meeting took place. So this is closed
