### ISSUE TITLE
PaNOSC logo

### ISSUE THREAD

**Issue by NicolettaCarboni** [panosc-eu/panosc#28]
The website's supplier has provided some proposals for the PaNOSC logo. 

[Here](https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP9%20Outreach%20and%20communication/PaNOSC%20logo/Panosc_Logo_Proposals_forselection.pdf) is the file where you can see all proposed options. 

Please send your first three preferences, by indicating the numbers of your favourite logo's proposals (you'll find the number of each proposal at the top right of each page).

The 1st one in the file is the one suggested by the supplier, and with which a first proposal of the website's layout has been already proposed. You can see it [at this link](https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP9%20Outreach%20and%20communication/PaNOSC%20website/Panosc_01-Home_v1.pdf)

**Comment by floriangliksohn** [comment]
No secret ballot? Alright, here's my vote:
- 4
- 2
- 1

I'll share with my PR department to get their vote as well.

**Comment by tizianaferrari70** [comment]
N1: 1
N2: 6
N3: 4

**Comment by JBodera** [comment]
n1: 2
n2: 6
n3: 4

**Comment by RDimper** [comment]
1. *3*
 2. *4*
 3. *2*

**Comment by perrin1024** [comment]
#1. 1
#2. 6

**Comment by NicolettaCarboni** [comment]
Dear all, I'd suggest to keep the poll open until Friday at the latest. Please let me know whether I should add someone else to the participants' list in this issue

**Comment by andygotz** [comment]
* 1. 4
* 2. 2

**Comment by fangohr** [comment]
1. 6 
2. 2
3. 4

**Comment by andygotz** [comment]
None of the logos has enough votes. We need to define a minimum number of votes for a logo to be considered well chosen. I propose at least 30% of votes should agree on a logo for it to be adopted. Currently logos 1 and 4 have 2 of 8 votes i.e. 25% - not enough to say we have a winner.
We must invite all WP leaders to vote.

**Comment by NicolettaCarboni** [comment]
Please find at this link the results of the first poll, in which 6 out of 10 people voted for the 1st option:  https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP9%20Outreach%20and%20communication/PaNOSC%20logo/LogoSelection_poll.xlsx
The supplier could provide a last proposal starting recalling the previous logo, for which some feedback from you is needed. On this regard, may I remind you to please fill in the short questionnaire at this link: https://docs.google.com/forms/d/e/1FAIpQLScGkf7vH4mFhILRLLkgLpR0P_7pYAdrXbXl-9lNnEGe3CFK9A/viewform?usp=sf_link at your earliest convenience and possibly before tomorrow (Friday 1/03), at 3pm

**Comment by NicolettaCarboni** [comment]
All PaNOSC logo formats are available at this link: https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP9%20Outreach%20and%20communication/PaNOSC%20logo
