### ISSUE TITLE
Questions to FairsFair

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#34]
This issue gathers the question we propose to ask the FairsFair community. FairsFair is an h2020 project to help communities adopt the FAIR principles (see https://www.esfri.eu/sites/default/files/Infrid%20Dillo.pdf).

Following questions have been proposed by the PaNOSC members (mostly WP2):

1. How to make FAIR data policies GDPR compliant?
2. What assistance can FairsFair provide in reviewing data policies?
3. What certification will FairsFair provide?
4. Which of the FAIR recommendations should be integrated directly into data policies?
5. Will FairsFair provide a template data policy or make a catalogue of FAIR compliant data policies?
6. What does FAIR compliant mean for data policies?

Please add questions to this issue by continuing the numbering.

**Comment by perrin1024** [comment]
We could probably also extend the scope to WP3, they mentioned in their slides "Support the “FAIRification” of repositories by extending repositories interfaces to comply with FAIR practical guidelines"
7. How to work practically with them in this area? what are their schedule?

They also mentioned metrics and interoperability in the slides referenced by Andy
8. What does it means for us? Are they going to provide APIs that we will have to integrate in our services?

**Comment by JBodera** [comment]
9. Is there going to be a FAIR score? 

I mean, we may or may not reach certification level, but it would be good to have some sort of scoring, so we can all compare ourselves (and maybe compete for the highest score).

**Comment by andygotz** [comment]
10. What is the difference between FAIRsFAIR and GO-FAIR? Who should we work with?

**Comment by andygotz** [comment]
@Jon-Taylor did you get any answers to our questions at the FAIRsFAIR kickoff?

**Comment by Jon-Taylor** [comment]
**Feedback from the FairsFair Kickoff.** 
I’ve itemised this in alignment with the questions that we collated. I presented the questions during the cluster presentations, at that point there were no clear answers, so what is below is a collation of information from throughout the meeting, and the parallel sessions i attended.

**1. How to make FAIR data policies GDPR compliant? **
Many people mentioned GDPR, some attendees mentioned that they felt GDPR was a non issue. So long as those who had personal data stored were informed and there was a method in place to review stored personal data and remove it when it became stale, or removal was requested.
I am not a GDPR expert but have been led to believe that GDPR is more involved that this assessment. In short FF are as much in the dark as everyone else. 

**2. What assistance can FairsFair provide in reviewing data policies? ** 
 FF WP3 will collate / review the current policy best practice and policy landscape to generate some high level recommendations. This work has not started and most of the discussion was how to get data and how to interface with unknown groups. I suggested that we send WP3 of FF our WP2 data policy assessment. FF will generate recommendations on best practice 

**3. What certification will FairsFair provide? **
Specifically the project will not certify anything. WP2 will issues a call for repos that require assistance to get core trust seal certification. CTS is what will be used to certify compliance. We have to wait for the call. It was communicated that not all repositories would be considered for this.

**4. Which of the FAIR recommendations should be integrated directly into data policies?**
(See answer to two - there will be recommendations)

**5. Will FairsFair provide a template data policy or make a catalogue of FAIR compliant data policies?** 
The landscape is so large i.e. FF looks at everything. most deliverables are reports. There will be no generic template

**6. What does FAIR compliant mean for data policies? **
This is something that will be defined through best practice recommendations in WP2 and Wp3

**7. How to work practically with them in this area? what are their schedule? **
The overall schedule matches Panosc, waiting for FF for information / and deliverables would be tricky.  Their consortium is large and many details of what was actually going to get done are still unclear. 
There will be a panel with representatives from the clusters and 5b projects (Knut from Expands attended but was always in other meetings). I think it would be sensible to invite FF reps to the panosc general meetings. Their annual meeting is the same time as ours, and will probably be a satellite to the RDA meeting in Finland. 

**8. FF mentioned metrics and interoperability **
What does it means for us? Will FF provide APIs that we will have to integrate in our services?
Interoperability is covered by wp2, they will work on standards for meta data, but at a high level. It was very unclear who this should work for our domain. the FF team don’t understand our domain and were constantly asking how we dealt with meta data. 
They will organise a meeting to discuss meta data standards, Panosc WP3 should attend that. 
There was no mention of an API being a deliverable, I asked about compliance with standards and didn’t get very far. 
WP2 of FF deals with catalogue integration although it was unclear what actually will be delivered in this regard 

**9. Is there going to be a FAIR score. **
No there will be best practice and certification through CTS
10. What is the difference between FAIRsFAIR and GO-FAIR? Who should we work with? 
This question is answered I think by the overall eosc governance diagram go-fair services are represented by eosc-secritariet.  The clusters and 5b projects should collaborate with fairs fair. 

Overall the meeting was quite intense, there was not a clear communication on what was really going to be delivered, there was a clear indication that the cluster projects were viewed as key stakeholders. 
There were many comments regarding fair software, I felt this was not addressed in the proposal, nor at the meeting
One way to proceed would be for panosc to generate ( in collaboration with expands) a position paper on how fair should be implemented in our domain,  and drill into the details and complexities of our meta data. - There is no understanding on this from FF and it is viewed as not in their project scope.

**Comment by JBodera** [comment]
As per PMC meeting 10/04/2019 this is now closed
