### ISSUE TITLE
PaNOSC website development

### ISSUE THREAD

**Issue by NicolettaCarboni** [panosc-eu/panosc#35]
Please have a look at the first draft of the website layout in the PaNOSC Google drive at this link:
https://drive.google.com/drive/folders/1R2vivDAoT2D8Euk4H8eTCVhPVdxz5-vH

INFO:
- At the bottom of the homepage, partners' logos will be displayed differently from how you see them now, and will be rather placed in one single line, which may be scrolled horizontally (see example at the bottom of the CERIC homepage https://www.ceric-eric.eu >> projects and collaborations)
- PaNOSC will not have its own newsletter. Therefore, that section in the homepage will be deleted. At the top right of the page, instead of "Newsletter signup", there will be a link "Contact us" redirecting to the related section (under "About")
- "Use cases" and "Women in Science" stories will be displayed in a similar template as the news' one (to see the example, follow this link > https://drive.google.com/open?id=1AicK3_Ic9jCo9YVF9pz3fYCeCqpI08dH
- The top menu will not be clickable in the first level, and rather only in the sub-items listed with mouse-over.
- Permissions in the backend can be given to editors (seeing, modifying and publishing) and contributors (seeing and modifying, without publishing). Later on and before of the release of the website, we will need to define who will have access to the backend as editor and contributor. I would keep the number of editors limited (e.g., 3-5 people max.).

QUESTIONS:
- In the contacts' page, we may include - in addition to the list of PaNOSC contacts (contact@panosc.eu, management@panosc.eu + all wp leaders' contacts) - also a contact form, in which whomever has questions may select the related topic from a drop-down menu. To each item, one (and only one) email address may be assigned. It could be that of the related WP. Alternatively, the contact form may be implemented for general enquiries only, which may all be directed to one single address (e.g., contact@panosc.eu)

**Comment by jamhall** [comment]
Hi @NicolettaCarboni. 

The website looks great! I particular like the services page and the services logos. Will it also be responsive (for mobiles)?  Is that the chosen logo or are we still going through the selection process?

**Comment by NicolettaCarboni** [comment]
@jamhall glad that you like it. 
Yes, the website will be responsive.
As for the logo, this is not the one selected yet. There will be a final poll hopefully sent within today or tomorrow.

**Comment by NicolettaCarboni** [comment]
@jamhall since you've asked about the logo and nobody from ILL voted yet, please send us your preference by filling in the questionnaire at this link > https://docs.google.com/forms/d/e/1FAIpQLSc1uoweCtrcpS-hY24r8pkNGve9OWEzvbDP2PEZP3NO1jjeeQ/viewform?usp=sf_link

**Comment by NicolettaCarboni** [comment]
Here the 1st beta version of the PaNOSC website:
http://panosc.clientspace.it/

**Comment by NicolettaCarboni** [comment]
Please find at this link the files with the draft content for the PaNOSC website: https://drive.google.com/drive/folders/1Vux1AeN5enhxo-OkbXi85UUrLjntGVoi
The sections "About" and "Data Policy" have been already uploaded in the beta version of the website at http://panosc.clientspace.it/

In the case you'd like to make further changes, please ensure they are highlighted, so that I can find them easily, and possibly send me a notice via email or reply to this post, so that I can see when they are implemented.

For the section "Developments", does anyone volunteer to write a first draft with a general description of the related work that will be carried out? 

For the "services" section, I'll try to provide a first draft with brief general descriptions of the different services' types possibly by the end of next week.

**Comment by NicolettaCarboni** [comment]
Here at this link >> https://drive.google.com/open?id=1QdzpkZjrNt8bAxs6sQG0xZU6ajWAEpO52QkrJL4etnc << is the first draft of the brief descriptions for the different service categories that we will offer in the frame of PaNOSC, to be published in the project website. 
As you will see, the texts are very brief, since this page should only give a brief overview of what we'll provide, inviting the user to proceed navigating and discovering/using the available services. 

A more detailed description will be included in a "new page", as specified in the file (one per each service category). In particular for this second part, I'd need your help and input. I'd propose WP leaders (and specifically leaders of WP3, WP4, WP5 and WP6) to give their contribution to draft the content linked to their WP.

It would be useful if you could check the text and make your changes possibly before the end of next week.

**Comment by andygotz** [comment]
I have made some improvements to the text about data services in a copy of the document here:

https://docs.google.com/document/d/1QsDLBETaJu7UOKSkIoSUrDLLBTI5hi925sBqcNNHDUM/edit?usp=sharing

I agree it is good to keep the text short and only add stuff in the dedicated pages.

**Comment by JBodera** [comment]
website is up. I close this issue. If further work is required in the website a new issue can be created.
