### ISSUE TITLE
PaNOSC Executive Board & Project Management committees

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#4]
Dear all,

We still have not finished our Consortium Agreement (our legal team is working on it), however as per our Proposal and the draft that we shared previously **we plan to have an Executive Committee* with one member from each Consortium partner** (ESRF, ILL, XFEL.EU, ESS, ELI, CERIC-ERIC and EGI).

**We need to sort out who is going to fulfill this role for each partner**, ideally he/she will be a senior member of the institution not directly involved in any of the work packages.

This issue is just a reminder that we still do not have the nominated people for the Executive Committee*.

**PLEASE NOTE:**  The Executive Committee (EC) has been renamed Executive Board (EB) in order to do not have the same acronym as the European Commission that funds the project.

**Comment by petraaulin** [comment]
From ESS this will be Jonathan Taylor, head of DMSC

**Comment by floriangliksohn** [comment]
I will fill that role for ELI for the time being.

**Comment by JBodera** [comment]
Hi @floriangliksohn , 
> 
> I will fill that role for ELI for the time being.
>
That's good, however I would like to point out that we would like to have two separate bodies:
1st - An Executive Board that meets once/twice a year to review progress and obtain updates
2nd - A Project Management Committee that runs and coordinates the project on a daily basis and that reports to the Executive Committee

Therefore I was thinking that members of the 1st body do not belong to the 2nd.

@petraaulin , that's perfect thanks

Kind regards,
Jordi Bodera

**Comment by floriangliksohn** [comment]
Thanks Jordi. I will take your comment into account and consult internally. Back to you shortly.

**Comment by floriangliksohn** [comment]
Project Management Committee: Florian Gliksohn
Executive Board: Allen Weeks (ELI-DC Director General)

**Comment by fangohr** [comment]
Sandor Brockhauser is the contact for EuXFEL.

**Comment by JBodera** [comment]
OK,

So far we have ( the latest version is available on https://github.com/panosc-eu/panosc/wiki/PaNOSC-Stakeholders )

| Partner | Project Management Committee Member  | Executive Board Member |
| ------- | ------------------------------------------- | -------------------------------  |
| ESRF | Andy Gotz | Rudolf Dimper |
| ILL | _Jean-Francois Perrin ?_ | Mark Johnson |
| EuXFEL | Hans Fangohr  |  Sandor Brokhauser |
| ELI-DC | Florian Gliksohn | Allen Weeks |
| ESS | Petra Aulin |  Jonathan Taylor |
| CERIC-ERIC | Dario Roccella | Jana Kolar  |
| EGI | Diego Scardaci | Tiziana Ferrari |

Please reply to this and I will update the table

**Comment by GeorgeElettra** [comment]
Thank you Jordi! Please update the table by exchanging the names of Kolar and Roccella. It should appear as following!

| Partner | Project Management Committee Member  | Executive Board Member |
| ------- | ------------------------------------------- | -------------------------------  |
| ESRF | Andy Gotz | Rudolf Dimper |
| ILL | _Jean-Francois Perrin ?_ |  |
| EuXFEL | Hans Fangohr  |  Sandor Brokhauser |
| ELI-DC | Florian Gliksohn | Allen Weeks |
| ESS |  |  Jonathan Taylor |
| CERIC-ERIC | Dario Roccella | Jana Kolar |
| EGI | Diego Scardaci | Tiziana Ferrari |

**Comment by JBodera** [comment]
Thanks @GeorgeElettra, this has been noted.

**Comment by JBodera** [comment]
Just to let you know that we plan to send letters to the Director General (or equivalent) of each partner institute to ensure that staff members nominated to PMC and EB have a formal appointment letter from their institute.

**Comment by petraaulin** [comment]
Hey @JBodera - We are a bit confused about the weekly meeting and the Project Management Committee. 1. Is the weekly meeting for the WP-leaders or for the PMC? 2. Is therea clear definition of the role of the PMC? Where can I find it?

**Comment by JBodera** [comment]
Hi @petraaulin 

Most of the PMC members are also WP leaders, so we will continue for now with the PMC meeting having the WP leaders invited. If we need to take a decision on how to proceed, then only PMC members would get a vote. If we realise that this structure doesn't work then we will change it. For now the meetings seem useful to me, so I would continue with them.

The draft Consortium Agreement includes definitions for the Executive Board and PMC.

Thanks,
Jordi

**Comment by JBodera** [comment]
As per PMC 23/01/2019 I close this issue
