### ISSUE TITLE
Update KPIs

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#41]
The Key Performance Indicators (KPIs) in the proposal need to be updated to take into account any changes at the partner sites and to include new more fine grained ones. The goal is to have KPIs which allow us to measure the real impact of FAIR and PaNOSC.

**Comment by andygotz** [comment]
I propose the following KPIs for WP2:

- number of instruments on which Data Policy is implemented
- number of techniques / instruments for which metadata are defined
- number of metadata parameters defined
- number of raw data DOIs 
- number of user defined DOIs
- number of downloads 
- number of citations of DOIs
- number of datasets
- volume of data archived
- number of DOIs for processed data

Some of these could be linked to other WPs.

**Comment by fangohr** [comment]
Some more suggestions:
- fraction of facilities offering a JupyterHub or Remote Desktop service for analysis
- users making use of this service (either through unique IDs, or counting each time they login)
- number of data analysis tools available through remote services (Jupyter / VISA). [Could also use 'number of distinct data analysis procedures' - but that's harder to decide: at what point does a minor alteration of a parameter/method establish a new procedure.]

**Comment by fangohr** [comment]
We could also consider 'qualitative indicators': these can be short reports describing a situation (not quantitative). For example, one could interview users of our services and summarise what they think of the provision. It is a lot more work for everybody - need to question if it is worth it.

**Comment by JBodera** [comment]
Please do update the list on: https://docs.google.com/spreadsheets/d/1iivsvBrix4v6lmC2U3sOC6YEXFeY0JzXHTM9QQQZwiY/edit#gid=2060225314

**Comment by thomasholmrod** [comment]
We will discuss this for WP8 at our next weekly meeting

**Comment by thomasholmrod** [comment]
A number of KPIs have been added for WP8

**Comment by JBodera** [comment]
As of 13/12/2019 KPIs obtained from all WPs (except WP3 and WP7), with few information missing for the other KPIs.

It may be a good idea to put the KPIs in the PaNOSC website, so everyone can see how are we doing and what are our targets.

**Comment by JBodera** [comment]
I will close this issue as we have a new one for joint KPIs with ExPaNDS #63

**Comment by JBodera** [comment]
I will close this issue as we have a new one for joint KPIs with ExPaNDS #63
