### ISSUE TITLE
Internal Milestones / deliverables

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#43]
Dear all,

As per PMC 19/06/2019 please collaborate with suggested Milestones/ deliverables in your work package.

We do not want to have these every other week, but rather fill in the gaps when milestones/deliverables in a work package are separated for over 6 months. As a rule of a thumb if a WP has nothing to show/deliver over six months ideally we would add an internal deliverable/milestone to track progress.

**Comment by andygotz** [comment]
I have checked the Tasks and Milestones and propose as a first iteration the following intermediate Milestones:

* **WP2**
   1. MS2.1a - draft of new data policy framework (M12)
   2. MS2.2a - plan of how the DP will be adopted at all sites (M18)
   3. MS2.4a - draft of guidelines for DP best practices (M12)
   4. MS2.5a - DMP design (M24)
   5. MS2.6a - DP adoption status report (M24)
   6. MS2.7a - DMP online (M36)
* **WP3**
   1. MS3.2a - specification of API (M12)
   2. MS3.4a - demonstrator of federated search (M20)
   3. MS3.5a - federated search implemented 50% (M32)
   4. MS3.6a - HDF5 meeting (M12)
* **WP4**
   1.  MS4.1a - architecture and design of DAAS (M12)
   2. MS4.2a - web visualisation demonstrator (M30)
* **WP5**
   1. MS5.1a - containers for simulation services (M12)
   2. MS5.2a - infrastructure for simulation services (M24)
   3. MS5.2b - report on user feedback of simulation services (M36)
* **WP6**
   1. MS6.1a - AAI prototype (M12)
   2. MS6.2a - data transfer demonstrator (M12)

**Comment by thomasholmrod** [comment]
We will discuss internal milestones for WP8 at our next weekly meeting

**Comment by thomasholmrod** [comment]
**WP8**

Tentative, should be reviewed and updated twice a year at the WP meetings

1. VC in preparation for annual meeting completed (M10)
2. Solution for Jupyter integration found [T8.2] (M13)
3. Budget clarification for hardware [T8.1] (M14)
4. Mid-year VC completed (M18)
5. MS8.4 moved forward to end of 2020 [T8.2] (M25)
6. Wish-list from partners defined [T8.3] (M13)
7. Workshop scheduled [T8.3] (M15)
8. First facility specific course integrated [T8.3] (M18)
9. Course / tutorial using Jupyter developed [T8.2 / T8.3] (M25)
10. Mid-year VC completed (M30)
11. 2nd facility specific course integrated [T8.3] (M31)
12. Mid-year VC completed (M42)

**Comment by NicolettaCarboni** [comment]
Proposal of WP9 internal milestones:
*Report on Y1 outreach activities published (M13)
*All website sections completed (M12)
*First use cases (2-3) published on the website (M12)
*List of user meetings, where PaNOSC/ExPaNDS goals/achievements will be presented, defined (M12)

**Comment by JBodera** [comment]
I have created the document on https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP1%20Management/Plans/PaNOSC%20Gantt%20with%20internal%20milestones.xlsx which contains a tab called Gantt (last tab) showing the Internal Milestones alongside the deliverables.

EDIT: The word document in the same folder: https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP1%20Management/Plans/PANOSC%20Tasks%2C%20Deliverables%20and%20Milestones.docx contains an easier to print summary of the Tasks, Deliverables, Milestones and Internal Milestones over four pages.

**Comment by JBodera** [comment]
Tobias sent this through 06/10/2019:
>>
WP3 Data Catalogue Services	

Delete these placeholders:
	* IMS3.2a	specification of API (M12)
	* IMS3.4a	demonstrator of federated search (M20)
	* IMS3.5a	federated search implemented 50% (M32)
	* IMS3.6a	HDF5 meeting (M12)

I could not see our "official" milestones in the documents. They are:
	M12		MS3.1 Survey of APIS and Roadmap to EOSC
	M12 		MS3.2 Ontology Feedback to API Tasks
	M30 		MS3.3 Catalogue Integration Best Practices

Add:
	M12 		WP3 Meeting at GA
	M16		API Feedback from ExPaNDS
	M16		Community Meeting on NeXus Ontologies
	M24 		WP3 Meeting at GA
	M24		Draft of Proposed Metadata Schema for Harvesting Services
	M33		ExPaNDS Catalogue Release
	M36 		WP3 Meeting at GA
<<

**Comment by JBodera** [comment]
I think that this can now be closed as we are in the last year of project execution
