### ISSUE TITLE
CERIC link on panosc website 

### ISSUE THREAD

**Issue by JunCEEE** [panosc-eu/panosc#44]
Hi, 

This is Juncheng. I have just started working on WP5 at European XFEL from July. I just happened to find the logo link of CERIC on https://www.panosc.eu/ does not work. The correct link might be https://www.ceric-eric.eu/ instead of http://www.ceric-eric.com/?

Best,
Juncheng

**Comment by NicolettaCarboni** [comment]
The issue has been solved and can be closed
