### ISSUE TITLE
Review Meeting details

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#52]
This issue is to clarify details for the review meeting to take place around month 18 of project execution.

1st detail to clarify with our project officer is : **What is the exact date for the Review Meeting?** 
If no exact date can be provided, at least a confirmed range of dates would be helpful, the smaller the range the better.

*Unrelated to this issue, Andy could ask our Project Officer whether PaNOSC can sponsor events that attends as well*

**Comment by andygotz** [comment]
The exact date of the virtual (remote participation only) is fixed for the 16 June (whole day).

We will probably use zoom as the platform.

Some ideas for a schedule to start the discussion:

1. Welcome - PO + PC
2. PaNOSC overview - Andy (20')
3. Project management review - Jordi (30')
4. Data Policy - Andy (20')
5. Common search API definition + demo - 40'
6. Data Services progress and demo - 90'
7. Simulation services progress and demo - Carsten + Juncheng (60')
8. Connecting to EOSC - Jean-Francois+EGI+GÉANT (40')
9. Training platform progress and demo - Thomas (40')
10. PaNOSC sustainability - Ornela (20')
11. PaNOSC communications - Nicoletta (30')

**Comment by JBodera** [comment]
> 
> 
> The exact date of the virtual (remote participation only) is fixed for the 17 June (whole day).
> 

Did you mistype? 17th June is Wednesday (JF Perrin not available) and we did agree on Tuesday16th June.
I will reference this issue from the meeting agendas that are focused on the Review Meeting.

**Comment by andygotz** [comment]
Sorry my mistake - I meant 16 June 2020 ! I have corrected it.

**Comment by JBodera** [comment]
Doodle status as of 22/04 for the rehearsal:

![image](https://user-images.githubusercontent.com/42926461/79952856-5596a000-847b-11ea-9505-db7301781729.png)

**Comment by JBodera** [comment]
Draft WP4 presentation for rehearsal meeting: [WP4-intro-fangohr.pptx](https://github.com/panosc-eu/panosc/files/4712783/WP4-intro-fangohr.pptx)

Draft WP1 presentation 
[PaNOSC_WP1_ReviewMeeting.pptx](https://github.com/panosc-eu/panosc/files/4721833/PaNOSC_WP1_ReviewMeeting.pptx)

**Comment by NicolettaCarboni** [comment]
[Draft WP9 presentation](https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP9%20Outreach%20and%20communication/Presentations/M18%20Review%20Meeting/WP9-PaNOSC_NCarboni_2020ReviewMeeting.pdf)

**Comment by CFGrote** [comment]
[Daft WP5 presentation](https://github.com/panosc-eu/panosc/raw/master/Work%20Packages/WP5%20Virtual%20Neutron%20and%20X-ray%20Laboratory/Documents/Presentations/WP5_18MReview.odp)

**Comment by JBodera** [comment]
As of 04/09/2020 we are still awaiting feedback, however the meeting went well
