### ISSUE TITLE
Kick-off meeting planning

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#6]
Dear all,

This issue is about the need to sort out all the planning for our Kick-off meeting, currently scheduled to take place 15th January in Grenoble.

As of now, I can think of the following areas pending confirmation:

1. Agenda
    1.a One or Two day event?
    1.b We need a draft agenda
2. List of attendees per partner
3. Organiser bookings
    3.a Meeting rooms / areas
    3.b Meals / restaurants
    

Thanks

**Comment by JBodera** [comment]
Hi,

Regarding the agenda I propose a two day event:
1. Executive Committee members will only be required the first day for a signing ceremony and looking at what is PaNOSC and where we are
2. The rest of us involved in the day to day running of PaNOSC will review where we are (risks, work packages, etc.) in order to try to add more detail to the Project and create a detailed plan.

So far, I have this draft agenda: https://indico.esrf.fr/indico/event/19/

**Comment by petraaulin** [comment]
are we also inviting the staff that will work on the project?

**Comment by JBodera** [comment]
Hi Petra,
> 
> are we also inviting the staff that will work on the project?
>
I would suggest that to this meeting we invite:
1.- Executive Committee Members (1 per partner, so 7 in total)
2.- The usual attendees of the video conference calls
3.- If a parner wants to invite further people that's OK and it will come out from their budget allocation for travel

Anyone that is and will be heavily involved in the project and can and want to contribute to this initial stages is welcome from my point of view.

**Comment by RDimper** [comment]
I think that the Kick-off meeting is an important opportunity to make the project known. I therefore suggest that we also invite the Observers, representatives from the EC, the coordinators of the other INFRAEOSC04 projects and, as suggested, staff who will work on the project.

**Comment by andygotz** [comment]
I fully agree with you Rudolf about the list of invitees. I would add PaNOSC users too. We are doing it for them so it is necessary to have them on board from the beginning. We need to decide who invites whom now.

I have updated the agenda following the suggestions made during the last video meeting:

https://indico.esrf.fr/indico/event/19/

Please add your comments and suggestions on the agenda to this issue.

**Comment by fangohr** [comment]
I like the split into a 'public' day and an internal working day on day 2.

For day 2, I think it would be useful to have break out sessions where key people for individual work packages can get together, get to know each other (and the respective skills, and the interests and requirements from each partner), and also plan how to divide work within the work package most effectively. Essentially, a couple of hours of unstructured time in smaller groups. I could imagine that a little more time than 90 minutes would be useful, but it's not essential, and will depend on the group size for each WP.

What is planned in WP9: Communication? To whom do we feedback?

**Comment by petraaulin** [comment]
where can I find the list of registered participants for the kick-off?

**Comment by JBodera** [comment]
@RDimper or @andygotz , can you please help Petra with her query about the registered attendees?
Thanks,

**Comment by JBodera** [comment]
As per PMC 23/01/2019 I close this issue
