### ISSUE TITLE
Review Report: Engage the community

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#62]
In the section 1.4, the review report reads:
_ It does not make much sense to make recommendations for a past time, however, some lessons learned could be applied or taking into account, for example, searching for new mechanisms to engage the community (the so-called “users”) in the FAIRification of data and the re-use and citation of Photon and neutron datasets. Better user involvement, through open educational resources, might be explored._

We should clarify how are we going to engage with users, be specific about these actions with timescales and someone nominated to be owning each task. 

Examples of what can be done:
* Engage with users to obtain use cases
* Organise user-centric workshop / meetings
* Plan to target user meetings via presentations / demos

**Comment by NicolettaCarboni** [comment]
I would slightly rephrase your sentences as follows (and add few more):
- Engage with users at PaNOSC PaN facilities to identify success stories in the adoption of FAIR data practices, and publish related use cases;
- Organise user-centric workshop / meetings (WP8) and attract participants from the PaN community (WP9);
- Target user meetings at PaN facilities more widely, via presentations / demos / showcase of use cases;
- Take part in conferences and events targeting the PaN user community (e.g. International Conference on Neutron Scattering, International Conference on Synchrotron Radiation Instrumentation, etc.);
- Present PaNOSC progress and achievements at the PaNOSC partners' scientific boards meetings;
- Promote PaNOSC services and policies via PaN networks, such as lightsources.org, neutronsouces.org, associations of users, etc.
- Connect with user offices at PaN facilities to timely inform them about PaNOSC relevant activities, events and achievements.

**Comment by JBodera** [comment]
No longer a major issue after M36 review
