### ISSUE TITLE
Review Report : DOI links

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#66]
The Review report in page 3 (section 1.5) reads:
_- Guarantee the persistent identification of all the public deliverables and outcomes of the project (for example, the DOI of the Data Policy Framework (https://doi.org/10.5281/zenodo.382604) does not work_

Also, in page 6 (section 4.4):
_• PaNOSC hast not published (at least yet) any scientific publication. However, in the Project Continuous Report, 8 “publications” are listed, all them as “gold” with is wrong, since they are not scientific publications and all of them are published as pre-prints in Zenodo. But one of them, even when listed as Gold Open Access, is a closed scientific peerreviewed, paper under a paywall. See: https://doi.org/10.1080/08940886.2019.1608119. (Following a written remark, the COO responded that the beneficiary in question is in the process of getting gold access.)_

Actions: 
* The DOI link for the DP Framework should be fixed ASAP
* Examine why/how we got the link wrong

**Comment by NicolettaCarboni** [comment]
This is the correct link: https://doi.org/10.5281/zenodo.3862701
All the references to the document have been checked in the PaNOSC website and are correct.

**Comment by JBodera** [comment]
In the PMC of 21/10/2020 it was clarified that the DOI was misspelled in the eu portal and that it is now sorted. ISSUE CLOSED.
