### ISSUE TITLE
Review Report : EOSC Stakeholders communications

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#67]
Review Report in page 3 (section 1.5) reads:
_- Keep, and even foster, the relationship with ALL (apart of ExPaNDS) EC funded project in the EOSC ecosystem. As said in the DoW, liaison and collaborate with other projects, is crucial. For example in order to re-use and/or complement generic training materials on FAIR principles, EOSC interoperability, etc. (WP9- CERIC agreed to explore which related activities exist in other EOSC projects)._

Possible actions:
* Ensure all cluster projects attend our Annual Meeting and that we attend theirs
* Invite cluster projects representatives to more workshops / events
* Maybe organise specific workshop / event just to catch up with cluster projects ?

**Comment by NicolettaCarboni** [comment]
The following may be added:
- Active participation in EOSC Secretariat's interest group "EOSC Cluster Collaboration" meetings, and related joint actions;
- Periodical meetings among coordinators of the cluster projects (already in place) and transfer of the relevant inputs to the leaders of WP comms/dissemination in the various projects, to ensure appropriate communications/dissemination of the set actions and achieved results.

With reference to the last WP9-related point mentioned ("CERIC agreed to explore which related activities exist in other EOSC projects"), the outcome of the action is the table available at this link > https://docs.google.com/spreadsheets/d/1vSLhxTEgLYyXSqtA1LDnbnANKHY1vLRaYea2ZEZOSgw/edit?usp=sharing
Next steps to use the information collected may be further discussed in the PaNOSC/ExPaNDS' partnership

**Comment by JBodera** [comment]
No longer an issue after M36 review
