### ISSUE TITLE
Review Report 2: Enhanced Federated Search Services

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#86]
Andy considers this a **Major Recommendation**, that is listed as the **Recommendation 8** in the _Recommendations concerning future work_.

The Feedback following the 2nd Periodic Report states:

_Future work in WP3 includes enhancements
to the federated search service in order to support dynamic access to the data sources (e.g., access to up-to-date data one
they become available). The consortium must make provisions for deploying and validating this enhanced service in at
least one of use cases that harness the federated search infrastructure._ on page 5

**Comment by zjttoefs** [comment]
Datasets do appear in the federated search dynamically as they become available. The federated search only gives access to data in public domain. That means the process through which data become available is exiting an embargo period or through explicit publication. I am not sure the reviewer had that in mind.

That isn't part of an existing use case, I am aware of.
